# Generated by Django 2.1.1 on 2018-09-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
