# Generated by Django 2.1.1 on 2018-09-07 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=50)),
                ('note_content', models.TextField(max_length=300)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Register1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_recycle', models.CharField(max_length=50)),
                ('register_place', models.CharField(max_length=200)),
                ('register_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Register2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_worker_name', models.CharField(max_length=50)),
                ('register_worker_place', models.CharField(max_length=200)),
                ('register_worker_age', models.PositiveSmallIntegerField(default=20)),
                ('recycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReciclaCoding_admin.Register1')),
            ],
        ),
    ]
