# Generated by Django 2.1.1 on 2018-09-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=50)),
                ('note_content', models.CharField(max_length=300)),
                ('note_date_publish', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Register1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_recycle', models.CharField(max_length=50)),
                ('register_place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_worker_name', models.CharField(max_length=50)),
                ('register_worker_place', models.CharField(max_length=200)),
                ('register_worker_age', models.PositiveSmallIntegerField(default=20)),
                ('recycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReciclaCoding_admin.Register1')),
            ],
        ),
    ]
