# Generated by Django 2.1.1 on 2018-09-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclaCoding_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_date_publish',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_content',
            field=models.TextField(max_length=300),
        ),
    ]
